package org.chronopolis.rest.models

import org.chronopolis.rest.models.enums.FixityAlgorithm
import java.time.ZonedDateTime

/**
 * A [Fixity] value belonging to a [File]
 *
 * @property value the value generated by the [algorithm] used
 * @property algorithm the [FixityAlgorithm] used
 * @property createdAt the [ZonedDateTime] the [Fixity] value was registered
 *
 * @author shake
 */
data class Fixity(val value: String,
                  val algorithm: FixityAlgorithm,
                  val createdAt: ZonedDateTime)

