INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-0', 'admin', 'test-depositor', 'STAGED', 1, 1, 3);
INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-1', 'admin', 'test-depositor', 'STAGED', 1, 1, 3);
INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-2', 'admin', 'test-depositor', 'STAGED', 1, 1, 3);
INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-3', 'admin', 'test-depositor', 'STAGED', 1, 1, 3);
INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-4', 'admin', 'test-depositor', 'STAGED', 1, 1, 3);
INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-5', 'admin', 'test-depositor', 'STAGED', 1, 1, 3);
INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-6', 'admin', 'test-depositor', 'STAGED', 1, 1, 3);
INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-7', 'admin', 'test-depositor', 'STAGED', 1, 1, 3);
INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-8', 'admin', 'test-depositor', 'STAGED', 1, 1, 3);
INSERT INTO bag(id, created_at, updated_at, name, creator, depositor, status, size, total_files, required_replications) VALUES (DEFAULT, CURRENT_DATE, CURRENT_DATE, 'bag-9', 'admin', 'test-depositor', 'TOKENIZED', 1, 1, 3);

INSERT INTO storage_region VALUES(DEFAULT, 1, 'BAG', 'LOCAL', 1000000, '', CURRENT_DATE, CURRENT_DATE);
INSERT INTO storage_region VALUES(DEFAULT, 1, 'TOKEN', 'LOCAL', 1000000, '', CURRENT_DATE, CURRENT_DATE);
INSERT INTO replication_config VALUES(DEFAULT, 1, 'test-server', 'test-replication-user', 'test-replication-path');
INSERT INTO replication_config VALUES(DEFAULT, 2, 'test-server', 'test-replication-user', 'test-replication-path');
INSERT INTO staging_storage VALUES(DEFAULT, 1, 't', 'bags/test-location', 1500, 3, CURRENT_DATE, CURRENT_DATE);
INSERT INTO staging_storage VALUES(DEFAULT, 2, 't', 'tokens/test-location', 1500, 3, CURRENT_DATE, CURRENT_DATE);
INSERT INTO fixity VALUES(DEFAULT, 1, 'test-alg', 'test-fixity', CURRENT_DATE);
INSERT INTO fixity VALUES(DEFAULT, 2, 'test-alg', 'test-fixity', CURRENT_DATE);
INSERT INTO bag_storage VALUES(1, 1);
INSERT INTO token_storage VALUES(1, 2);
INSERT INTO bag_storage VALUES(2, 1);
INSERT INTO token_storage VALUES(2, 2);
INSERT INTO bag_storage VALUES(3, 1);
INSERT INTO token_storage VALUES(3, 2);
INSERT INTO bag_storage VALUES(4, 1);
INSERT INTO token_storage VALUES(4, 2);
INSERT INTO bag_storage VALUES(5, 1);
INSERT INTO token_storage VALUES(5, 2);
INSERT INTO bag_storage VALUES(6, 1);
INSERT INTO token_storage VALUES(6, 2);
INSERT INTO bag_storage VALUES(7, 1);
INSERT INTO token_storage VALUES(7, 2);
INSERT INTO bag_storage VALUES(8, 1);
INSERT INTO token_storage VALUES(8, 2);
INSERT INTO bag_storage VALUES(9, 1);
INSERT INTO token_storage VALUES(9, 2);
INSERT INTO bag_storage VALUES(10, 1);
INSERT INTO token_storage VALUES(10, 2);

-- Create some distribution records too
INSERT INTO bag_distribution VALUES (1, 10, 1, 'DISTRIBUTE');
INSERT INTO bag_distribution VALUES (2, 10, 2, 'DISTRIBUTE');
INSERT INTO bag_distribution VALUES (3, 10, 4, 'DISTRIBUTE');
INSERT INTO bag_distribution VALUES (4, 10, 3, 'REPLICATE');
